### ISSUE TITLE
Interface para apresentar Iframes no Dashboard

### ISSUE THREAD

**Issue by IagoCarvalho** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#102]
## Descrição 
**Eu**, como usuário do sistema, **desejo** visualizar os gráficos gerados no metabase, **para** visualizar indicadores.

## Tarefas 
- [ ] Mostrar Iframes associados aos dashboards.

**Comment by Yoshida-Eduardo** [comment]
Criei um componente do vue js responsável por renderizar o Iframe, ele recebe como parâmetro o id da question no metabase.
