### ISSUE TITLE
Coletar o id dos fields de uma tabela no metabase

### ISSUE THREAD

**Issue by matheusbsilva** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#106]
## Descrição 
**Eu**, como desenvolvedor, **desejo** saber o id de todos os fields de uma tabela, **para** construir a query de filtragem.

## Tarefas 
- [ ] Pegar o id da tabela no metabase equivalente ao projeto no backend
- [ ] Fazer a requisição no endpot ```/api/table/:id/query_metadata``` para pegar informações sobre os fields

### Relacionado: 
- [Epic]()
- [Feature]()

**Comment by Yoshida-Eduardo** [comment]
Após várias tentativas de resolver a issue conclui-se que não é possível completar a issue por conta de problemas na compatibilidade das requisições feitas a partir do browser para a api do metabase.

Ao fazer uma requisição http o browser verifica se esta é uma simple request ou não. As simple requests não dão trigger na verificação de CORS e são enviadas diretamente ao servidor.

Para que a requisição seja uma simple request é necessário que todos os cabeçalhos presentes(além dos definidos automaticamente pelo User-Agent)  estejam na [safelist](https://fetch.spec.whatwg.org/#cors-safelisted-request-header).

Um dos cabeçalhos presentes nessa safelist é o Content-Type, mas só para os valores "text/plain, multipart/form-data, application/x-www-form-urlencoded", sendo que todos os demais valores dão trigger na verificação de CORS.

No caso do metabase é imperativo que o Content-Type nas requisições que contem um request body seja application/json(testado utilizando postman, curl e as bibliotecas vue-resource e axios), caso contrário a api do metabase não reconhece os dados enviados no corpo da requisição, logo por não se tratar de uma simple request a verificação de CORS irá ocorrer.

Por não se tratar de uma simple request o browser realiza uma requisição preflight, fazendo uma call com o método options para a api, que deve retornar um header "Acess-Control-Allow-Origin: *" para que a requisição inicial seja de fato enviada pelo browser. Entretanto a api do metabase não trata o método Options, impedindo que a requisição inicial seja realizada. 
![imagem](https://user-images.githubusercontent.com/37124267/41264642-27030ed8-6dc4-11e8-94cc-42a6136be0a3.png)

Para realizar essa issue é necessário realizar login na api do metabase que requer o Content-Type: application/json, mas como a API do metabase não trata o método OPTIONS a requisição não é completada, e para realizar o get no endpoint "/api/table/:id/query_metadata" é necessário utilizar o cabeçalho X-Metabase-Session que também não está na safelist, ocasionando o mesmo problema.

Logo não será possível implementar essa issue pelo front end que deverá ser feita pelo backend, 
pois é possível realizar a requisição diretamente sem a preflight request que é realizada pelos browsers.

Documentação sobre CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
Safelist: https://fetch.spec.whatwg.org/#cors-safelisted-request-header

**Comment by Yoshida-Eduardo** [comment]
A requisição na api do metabase para coletar os dados foi implementada em https://github.com/fga-gpp-mds/2018.1-TropicalHazards-BI/issues/347

Na presente issue foram adicionados os métodos para consumir os fields a partir da api do backend. Para fazer a call ajax deve-se utilizar: this.$store.dispatch("loadCurrentProjectFields", <dashboardId>). Os dados podem ser acessados através dos mapGetters getCurrentProjectFields que retornam um vetor com os fields do projeto atual.
