### ISSUE TITLE
implementar tela de criação de projetos

### ISSUE THREAD

**Issue by andre-filho** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#125]
## Descrição 
**Eu**, como --, **desejo** --, **para** --.

## Tarefas 
- [ ] Criar url 

## Critérios de aceitação 
- [ ] Cobertura de teste acima de 90% 

### Relacionado: 
- [Epic]()
- [Feature]()

**Comment by matheusbsilva** [comment]
Atualmente a tela de criação de projetos encontra-se com o seguinte bug de layout:
![](https://i.imgur.com/tIeAJZV.png)
![](https://i.imgur.com/cPWRPGQ.png)
