### ISSUE TITLE
Criação de projeto envia parâmetros obrigatórios vazios

### ISSUE THREAD

**Issue by matheusbsilva** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#137]
## Comportamento esperado 
Passar os parâmetros, não vazios,`name` e  `description` na criação de um projeto.
## Comportamento atual 
Parâmetros são passados vazios na criação do projeto
## Passos que levam ao bug
Logar, acessar a página de criação de projeto, preencher os campos corretamente, clicar em "Salvar".
## Print (opcional)
![](https://i.imgur.com/PniPbvd.png)

**Comment by Yoshida-Eduardo** [comment]
Resolvido no PR #141 foram adicionados as validações necessárias para não enviar campos obrigatórios vazios
