### ISSUE TITLE
Primeira página após o login mal formatada

### ISSUE THREAD

**Issue by matheusbsilva** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#139]
## Comportamento esperado 
Após logar acessar página com informações relevantes e bem formatada.
## Comportamento atual 
Página composta por extensão da sidebar com problemas de formatação.
## Passos que levam ao bug
Logar corretamente no sistema.
## Print (opcional)
![](https://i.imgur.com/HMZa2Pu.png)

**Comment by jppgomes** [comment]
Já foi resolvida
