### ISSUE TITLE
Implementar busca na landing page e sidebar

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#171]
## Descrição 
Implementar mecanismo de busca para as barras de busca da landing page e da sidebar, elas devem redirecionar para a dashboard list.

## Tarefas 
- [ ] Criar método de busca na landing page e sidebar
- [ ] Redirecionar para a Dashboard list passando como parâmetro o argumento de busca

**Comment by andre-filho** [comment]
feito
