### ISSUE TITLE
Configuração de ambiente de desenvolvimento front-end

### ISSUE THREAD

**Issue by arthur0496** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#2]
Tarefas 
  - [x] Criar Dockerfile
  - [x] Criar docker-compose
  - [x] Configurar com o ambiente do front-end

Depende desta [issue](https://github.com/fga-gpp-mds/2018.1-TropicalHazards-BI/issues/54)

**Comment by arthur0496** [comment]
Eu consegui subir o container com o front, mas não estou conseguindo espelhar porta

**Comment by arthur0496** [comment]
Eu rodei os testes dentro do container, então o ambiente ta funcionando la dentro, so não consigo acessar isso de fora

**Comment by matheusbsilva** [comment]
O server do Vue ta rodando no host localhost ou 0.0.0.0?

**Comment by alaxalves** [comment]
Consegui rodar o env de voces, pelo jeito a comunidade inteira de Vue ta tendo esse problema.

**Comment by arthur0496** [comment]
Funcionou @alaxalves , valeu pela ajuda
