### ISSUE TITLE
US - ui para inserção de csv

### ISSUE THREAD

**Issue by andre-filho** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#47]
## Descrição 
**Eu**, como usuário dono de um projeto, **desejo** inserir um arquivo csv no meu projeto, **para** salvar os dados da pesquisa.

## Tarefas 
- [ ] seguir prototipo

## Critérios de aceitação 
- [ ] Cobertura de teste acima de 90%

**Comment by Yoshida-Eduardo** [comment]
Instalei o plugin vue-js-modal para implementação da modal de inserção de csv e caixas de diálogo na branch
