### ISSUE TITLE
US - ui editar observatorio

### ISSUE THREAD

**Issue by IagoCarvalho** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#50]
## Descrição 
**Eu**, como usuário, **desejo** editar meu obserservatório, **para** atualizar o workspace.

## Tarefas 
- [x] implementar edit
- [x] feedback para usuário
- [x] confirmação antes de deletar

## Critérios de aceitação

**Comment by Maxlobo** [comment]
Issue duplicada.
