### ISSUE TITLE
Interface para definição dos dados

### ISSUE THREAD

**Issue by matheusbsilva** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#56]
#### Descrição

**Eu**, como usuário dono de um projeto, **desejo** definir o tipo dos dados importados, **para** assegurar a geração de indicadores.

## Tarefas

- [ ] Criar url
- [ ]

## Critérios de aceitação

- [ ] Todo dado deve possuir "Nome", "Descrição", "Tabela" e "Tipo"

- [ ] "Nome", "Descrição" e "Tipo" não podem ser nulos
- [ ] "Nome" não pode ser maior que 20 caracteres

- [ ] "Descrição" não pode ser maior que 200 caracteres

- [ ] "Tabela" pode conter zero, uma ou n referências
- [ ] Deve ser possível referenciar uma "Tabela" já existente no sistema
- [ ] Deve ser possível criar uma nova "Tabela"

- [ ] "Tipo" pode ser: "Booleano", "Flutuante", "GeoData", "Identificador", "Inteiro", "Lista", "Texto" e "Data"

- [ ] "Booleano" deve definir exatamente dois tipos de conteúdo, um verdadeiro e um falso. Ex: "Sim" e "Não", "Alto" e "Baixo", "0" e "1", "X" e "Y", "Homem" e "Mulher", "Verdadeiro" e "Falso"...
- [ ] "Booleano" deve possuir a opção: "Pode ser nulo?"
- [ ] "Booleano" deve possuir as seguintes opções exclusivas para "Transformar": "Não transformar elementos" (_Default_), "Transformar elementos para caixa alta" e "Transformar elementos para caixa baixa"

- [ ] "Flutuante" deve definir tipos de conteúdo numérico com frações. Ex: 1,000.2, 1.000,2, 1000.2, 1 000,2...
- [ ] "Flutuante" deve possuir a opção: "Pode ser nulo?"
- [ ] "Flutuante" deve possuir as seguintes opções exclusivas para "Separador de fração": "." (_Default_) e ","
- [ ] "Flutuante" deve possuir a opção: "Possui separador de magnitude?"
- [ ] Caso a opção "Possui separador de magnitude?" seja escolhida, "Flutuante" deve possuir as seguintes opções exclusivas para "Separador de magnitude": "," (_Default_), "." e " "

- [ ] "GeoData" pode ser: "Círculo", "Envelope", "Lista de Pontos", "Polígono" e "Ponto"
- [ ] "GeoData" deve possuir a opção: "Pode ser nulo?"

- [ ] "Identificador" pode possuir qualquer tipo de conteúdo ("String")
- [ ] "Identificador" não pode possuir conteúdo nulo
- [ ] O conteúdo do tipo de dado "Identificador" deve ser único
- [ ] "Identificador" deve estar associado a uma "Tabela"

- [ ] "Inteiro" deve definir tipos de conteúdo numérico sem frações. Ex: 1,000, 1.000, 1000, 1 000
- [ ] "Inteiro" deve possuir a opção: "Pode ser nulo?"
- [ ] "Inteiro" deve possuir a opção: "Possui separador de magnitude?"
- [ ] Caso a opção "Possui separador de magnitude?" seja escolhida, "Inteiro" deve possuir as seguintes opções exclusivas para "Separador de magnitude": "," (_Default_), "." e " "

- [ ] "Lista" deve definir tipos de conteúdo com múltiplos sub-conteúdos. Um exemplo bem prático são _tags_, que geralmente são definidas através de uma String onde cada _tag_ é separada por vírgula: "unb,fga,engenharia de software,eps,mds"
- [ ] "Lista" deve possuir a opção: "Pode ser nulo?"
- [ ] "Lista" deve possuir a opção: "Agrupar conteúdo em uma tabela?"
- [ ] "Lista" deve possuir o campo "Prefixo da lista", pode ser nulo se "Sufixo da lista" for nulo
- [ ] "Lista" deve possuir o campo "Sufixo da lista", pode ser nulo se "Prefixo da lista" for nulo
- [ ] "Lista" deve possuir o campo "Separador de elementos"
- [ ] "Lista" deve possuir a opção exclusiva "Tipo de elementos"
- [ ] "Lista" deve possuir as seguintes opções exclusivas para "Transformar": "Não transformar elementos" (_Default_), "Transformar elementos para caixa alta" e "Transformar elementos para caixa baixa"

- [ ] "Texto" deve definir tipos de conteúdo textuais
- [ ] "Texto" deve possuir a opção: "Pode ser nulo?"
- [ ] "Texto" deve possuir as seguintes opções exclusivas para "Transformar": "Não transformar elementos" (_Default_), "Transformar elementos para caixa alta" e "Transformar elementos para caixa baixa"

- [ ] Os tipos devem ser convertidos para elementos primitivos, com os adicionais de campos necessários para manter a coerência dos dados. Ex: "Booleano" deve ser convertido para `boolean`, mas deve manter as informações de texto para a condição verdadeira e para a condição falsa, além da informação se pode ou não ser nula

- [ ] Cobertura de teste acima de 90%

**Comment by arkye** [comment]
@Renatafsouza done

**Comment by Yoshida-Eduardo** [comment]
O component modal send data foi atualizado para enviar uma lista de dicionários com as informações sobre os cabeçalhos, conforme tornou-se necessário após a atualização da api no backend.
