### ISSUE TITLE
Efetuar validações utilizando o Vuelidate

### ISSUE THREAD

**Issue by jppgomes** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#59]
## Descrição 
**Eu**, desenvolvedor , **desejo**  implementar validações utilizando o **Vuelidate** em relação a:

## Tarefas 
- [ ] Validação para username - Criar usuário
- [ ] Validação para email - Criar usuário
- [ ] Validação para password - Criar usuário

- [ ] Validação para username - Editar usuário
- [ ] Validação para email - Editar usuário
- [ ] Validação para password - Editar usuário

- [ ] Validação para name - Criar Projeto
- [ ] Validação para description - Criar Projeto

- [ ] Validação para name - Editar Projeto
- [ ] Validação para description - Editar Projeto

- [ ] Validação para name - Criar Dashboard
- [ ] Validação para name - Editar Dashboard

## Critérios de aceitação 
- [ ] Cobertura de teste acima de 90% 

### Relacionado: 
- [Epic]()
- [Feature]()

**Comment by IagoCarvalho** [comment]
Issue ja resolvida
