### ISSUE TITLE
Implementar pesquisa por TAG

### ISSUE THREAD

**Issue by IagoCarvalho** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#70]
## Descrição 
**Eu**, como usuário, **desejo** digitar o nome de uma TAG em um campo e pesquisa da interface, **para** encontrar um projeto.

## Tarefas 
- [x] Implementar interface de TAGs

## Critérios de aceitação

**Comment by pdaniel37** [comment]
Issue resolvida no commit ec61bea.
