### ISSUE TITLE
Refatorar prototipo de alta fidelidade 

### ISSUE THREAD

**Issue by arthur0496** [fga-gpp-mds/2018.1-TropicalHazards-BI-FrontEnd#85]
## Descrição 
**Eu**, como desenvolvedor, **desejo** refatorar o prototipo de alta fidelidade, **para** melhorar a experiencia de usuário .

## Tarefas 
- [ ] Criar url 

## Critérios de aceitação 
- [ ] Cobertura de teste acima de 90% 

### Relacionado: 
- [Epic]()
- [Feature]()

**Comment by arthur0496** [comment]
Alterar criterios de aceitação e tarefas

**Comment by andre-filho** [comment]
como um prototipo pode ter 100% de cobertura?
